### ISSUE TITLE
Display of dynamics between the staves should be supported

### ISSUE THREAD

**Issue by aseipelt** [BeethovensWerkstatt/Verovio-Issues#3]
In piano notation often there is one dynamic sign for both hands/staves. To get a semantically correct encoding, we write the dynamics in an element that refers to both staves and the @place is "between". Verovio does not support the display of this yet, instead both  staves get the dynamic. 

example: Op. 38, mov. 6, measure 1
![Bildschirmfoto 2019-07-17 um 15 54 07](https://user-images.githubusercontent.com/12797475/61381639-a43f5a00-a8ab-11e9-898b-934c8d8cc380.png)

```xml
<dynam xml:id="x831b193b-ba68-456b-aedb-c4cc1d1c4f99" place="between" staff="4 5" tstamp="1">f</dynam>
<dynam xml:id="xf3f24ed5-cefa-46b2-b035-65808ec8b145" place="above" staff="5" tstamp="2.5">p</dynam>
```

**Comment by krHERO** [comment]
meanwhile this is already working
