### ISSUE TITLE
Collision of rests with other elements 

### ISSUE THREAD

**Issue by aseipelt** [BeethovensWerkstatt/Verovio-Issues#4]
When there are multiple layers, rests sometimes collide with other elements. Can they be flexible in height, depending on where the other elements are located?

see also:
rism-ch/verovio#617
https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/113#issue-332068033

**Comment by susannecox** [comment]
Some examples:
![T  89f](https://user-images.githubusercontent.com/40765557/67276473-0a4c0680-f4c5-11e9-863d-a6f72179c9f1.jpeg)
![T  12 1](https://user-images.githubusercontent.com/40765557/67276533-310a3d00-f4c5-11e9-9875-80c5ee080e1b.jpeg)

<measure n="12" xml:id="xb62e40f0-ebc2-4f67-ab5e-a9f0337a26e9">
                     <staff xml:id="x2bd7c2c4-52ee-47ac-9de5-6215c229628b" n="1">
                           <layer xml:id="x89d09c3c-1ee0-4203-be8e-edd747a13ec0" n="1">
                                 <note xml:id="x363b2b50-91ce-47d7-aac5-76bf73316953"
                                       pname="g"
                                       oct="3"
                                       dur="4"
                                       staff="2"
                                       accid.ges="s"
                                 />
                                 <note xml:id="x54b2bf2e-de93-47f8-a53a-6d623a4962a5"
                                       pname="g"
                                       accid="n"
                                       oct="3"
                                       dur="4"
                                       staff="2"
                                 />
                                 <note xml:id="xaaa3bd5f-e7f3-4d97-ade9-1354c930ae2c"
                                       pname="f"
                                       oct="3"
                                       dur="2"
                                       staff="2"
                                       accid.ges="s"
                                 />
                           </layer>
                           <layer xml:id="x8e5c0baf-fca5-4690-9684-b5ded38c75c8" n="2">
                           <note xml:id="xb93ee01d-feb8-4c05-b1f4-32cc3164ff4a"
                                 pname="b"
                                 oct="3"
                                 dur="1"
                                 />
                        </layer>
                        
                     </staff>
                     <staff xml:id="x43d53991-7ca6-433d-b8fc-c147ba4a587d" n="2">
                        <layer xml:id="x097239a5-19bf-4bb5-b051-fdbd225f434d" n="1">
                           <note xml:id="x29ec93f2-3706-4e59-b737-b47c4f998170"
                                 pname="b"
                                 oct="2"
                                 dur="2"
                                 />
                           <note xml:id="x35639a9f-d03f-4bba-b985-81ed45f00d31"
                                 pname="a"
                                 accid="s"
                                 oct="2"
                                 dur="4"
                                 />
                           <note xml:id="x16f3ff16-fdea-4c22-9a7f-d81b3150f660"
                                 pname="a"
                                 accid="n"
                                 oct="2"
                                 dur="4"
                                 />
                        </layer>
                           <layer xml:id="x4dfa559e-3b80-47e8-a1c5-f801074a5207" n="2">
                                 <note xml:id="x56542f23-6824-482b-8c9e-38103a165f99"
                                       pname="e"
                                       oct="3"
                                       dur="2"
                                       dots="1"
                                 />
                                 <note xml:id="x5125e689-47bc-4a83-8349-42149edc48c9"
                                       pname="d"
                                       oct="3"
                                       dur="4"
                                       
                                       accid.ges="s"/>
                           </layer>
                        <layer xml:id="xa42f6e4d-e247-4705-aad6-5a990caacbfe" n="3">
                           <rest xml:id="x40f46b5e-65cf-4767-8320-44a370e58baa"
                                 dur="2"/>
                           <note xml:id="xdf36fe80-6ce3-4cdd-ac10-977c880ce25e"
                                 pname="b"
                                 oct="1"
                                 dur="2"
                                 />
                        </layer>
                     </staff>
                     <slur xml:id="xb178d376-5c86-4e76-985f-06672667d8af"
                           startid="#x363b2b50-91ce-47d7-aac5-76bf73316953"
                           endid="#xaaa3bd5f-e7f3-4d97-ade9-1354c930ae2c"
                           
                           staff="2"/>
                     <slur xml:id="x816d87e9-02d3-4ffb-9940-5ed898d321c6"
                           startid="#x29ec93f2-3706-4e59-b737-b47c4f998170"
                           endid="#x16f3ff16-fdea-4c22-9a7f-d81b3150f660" 
                           curvedir="below"
                           staff="2"/>
                  </measure>

![T  51](https://user-images.githubusercontent.com/40765557/67276764-a70ea400-f4c5-11e9-93c6-5405d0334cbb.jpeg)

<measure n="51" xml:id="x1a08b9b5-d4aa-4853-82a5-fd7b0da5979f">
                     <staff xml:id="x938874b4-bc04-4d09-89e7-323cdc841655" n="1">
                        <layer xml:id="x2ae41b3d-bdb7-4981-9144-14e63348a0d9" n="1">
                           <note xml:id="x6412702e-4b39-4fda-8d44-a191e79b626e"
                                 pname="e"
                                 oct="4"
                                 dur="2"
                                 dots="1"
                                 />
                        </layer>
                        <layer xml:id="x28645f95-8bad-4520-82e5-68ceccc04f75" n="2">
                           <rest xml:id="xac633e93-ae2f-46f0-9855-e900874563ba"
                                 dur="4"/>
                           <rest xml:id="xb91ab907-7587-4882-b0a5-0ad2e23e70b9"
                                 dur="4"/>
                           <note xml:id="xb248fbcd-0567-4c3d-b118-d7edb9689a72"
                                 pname="g"
                                 accid="s"
                                 oct="3"
                                 dur="4"
                                 />
                        </layer>
                     </staff>

**Comment by krHERO** [comment]
the corresponding verovio issue was already closed https://github.com/rism-digital/verovio/issues/617
