### ISSUE TITLE
Rehearsal Letters

### ISSUE THREAD

**Issue by elisanovara** [BeethovensWerkstatt/Verovio-Issues#5]
Rehearsal Letters encoded with element <reh> https://music-encoding.org/guidelines/v4/elements/reh.html are not being displayed.

Example Op. 133:

![Bildschirmfoto 2019-07-23 um 15 02 01](https://user-images.githubusercontent.com/40852886/61714329-dbee4c00-ad5a-11e9-8f3f-e84c27eb5652.png)

![Bildschirmfoto 2019-07-23 um 14 58 50](https://user-images.githubusercontent.com/40852886/61714154-6f734d00-ad5a-11e9-94dc-fd0a5f7f773e.png)

**Comment by krHERO** [comment]
a solved verovio issue is here https://github.com/rism-digital/verovio/issues/1605 that suggests to use <rend/> inside <reh/>
i also checked the [code](https://github.com/rism-digital/verovio/issues/1605#issuecomment-734109240) example from craig and it works.
